### ISSUE TITLE
Centos 7 install fails

### ISSUE THREAD

**Issue by donttrustem** [opf/openproject-ce#4]
Hi,

I am trying to use the package for installation on Centos.   I have a clean server and installed mariadb manually.  I have setup the database and can login using the creditials but the install fails with the below error.  I am using localhost or mysql.

Thanks Mark

[openproject] ./bin/postinstall
rake aborted!
URI::InvalidURIError: the scheme mysql2 does not accept registry part: openproject:xxxxxxx (or bad hostname?)
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:36:in `initialize'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:270:in `new'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:270:in `resolve_url_connection'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:258:in `resolve_hash_connection'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:215:in `resolve_connection'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:151:in `block in resolve_all'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:150:in `each'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:150:in `resolve_all'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:69:in `resolve'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/core.rb:46:in `configurations='
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/core.rb:48:in `block in <module:Core>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/concern.rb:120:in `class_eval'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/concern.rb:120:in `append_features'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/base.rb:284:in `include'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/base.rb:284:in `<class:Base>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/base.rb:269:in `<module:ActiveRecord>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/base.rb:26:in `<top (required)>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-session_store-0.1.1/lib/active_record/session_store/session.rb:6:in `<module:SessionStore>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-session_store-0.1.1/lib/active_record/session_store/session.rb:4:in `<module:ActiveRecord>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-session_store-0.1.1/lib/active_record/session_store/session.rb:3:in `<top (required)>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-session_store-0.1.1/lib/active_record/session_store.rb:32:in `<top (required)>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/activerecord-session_store-0.1.1/lib/activerecord/session_store.rb:1:in `<top (required)>'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:85:in `require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:85:in `rescue in block in require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:68:in `block in require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
/opt/openproject/config/application.rb:66:in `<top (required)>'
/opt/openproject/Rakefile:33:in `require'
/opt/openproject/Rakefile:33:in `<top (required)>'
LoadError: cannot load such file -- activerecord-session_store
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
/opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
/opt/openproject/config/application.rb:66:in `<top (required)>'
/opt/openproject/Rakefile:33:in `require'
/opt/openproject/Rakefile:33:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by oliverguenther** [comment]
Hi @donttrustem,

sorry for the late reply - We don't use GitHub issues for tracking issues and support so this got lost.

For future reference, please use the OpenProject Forums (https://community.openproject.org/projects/openproject/boards/) for support and general questions to OpenProject.

If you found a bug in the application, you can report it on our community page: https://community.openproject.org/projects/openproject/

Regarding your issue, the actual error is `URI::InvalidURIError: the scheme mysql2 does not accept registry part: openproject:xxxxxxx (or bad hostname?)` and suggests that your `DATABASE_URL` is invalid.

Please check the output of `openproject run env` for the DATABASE_URL. It will likely contain an error that results in an invalid URL. You can correct that error by setting a new URL with `openproject config:set DATABASE_URL=mysql:/<...>`.

Best,
Oliver
